name: build

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: install ./cosign /usr/local/bin/cosign
      - run: install ./goreleaser /usr/local/bin/goreleaser
      - name: ghcr-login
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: caarlos0
          password: ${{ secrets.GITHUB_TOKEN }}
      - if: success() && startsWith(github.ref, 'refs/tags/')
        run: goreleaser release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
